---
- hosts: "{{host_app}}"
  remote_user: root
  vars:
    tomcat_version: tomcat
    user_id: qyy
  tasks:
    - name: Judgment  tomcat  directory
      file:
        path: "/home/{{item}}"
        state: directory
        mode: "u=rwx,g=rx,o=rx"
        owner: "{{ user_id }}"
        group: "{{ user_id }}"
      with_items:
        - tomcat
        - webapps
    - name: Judgment  webapps  directory
      file:
        path: "/home/webapps/apps-{{ app_id }}"
        state: directory
        mode: "u=rwx,g=rwx,o=rx"
        owner: "{{ user_id }}"
        group: "{{ user_id }}"
    - name: check | tomcat_home "{{app_id}}"
      stat:
        path: "/home/tomcat/{{app_id}}"
      register: tomcat_home
    - name: tomcat deploy
      unarchive:
            src: ../files/{{ tomcat_version }}.tar.gz
            dest: /home/tomcat/
            copy: yes
      when: tomcat_home.stat.isdir is not defined
    - name: 'F2 {{ tomcat_version }} >> {{ app_id }}'
      shell: cd /home/tomcat && mv -fu {{ tomcat_version }} {{ app_id }}
      when: tomcat_home.stat.isdir is not defined
    - name: '{{ app_id }} j2 >> conf'
      template:
            src: ../templates/server.j2
            dest: /home/tomcat/{{ app_id }}/conf/server.xml
            backup: yes
#ansible-playbook main.yml -i webservers.yml --extra-vars "host_app=portal app_id=portal tomcat_port=8080"
#ansible-playbook main.yml -i webservers.yml --extra-vars "host_app=bid app_id=bid tomcat_port=8082"
#ansible-playbook main.yml -i webservers.yml --extra-vars "host_app=sso app_id=sso tomcat_port=8084"
#ansible-playbook main.yml -i webservers.yml --extra-vars "host_app=utr app_id=utr tomcat_port=8081"
#ansible-playbook main.yml -i webservers.yml --extra-vars "host_app=utr app_id=flow tomcat_port=8085"
#ansible-playbook main.yml -i webservers.yml --extra-vars "host_app=utr app_id=cms tomcat_port=8088"
#ansible-playbook main.yml -i webservers.yml --extra-vars "host_app=utr app_id=gzq tomcat_port=8087"
#ansible-playbook main.yml -i webservers.yml --extra-vars "host_app=utr app_id=utrj tomcat_port=8086"
#ansible-playbook main.yml -i webservers.yml --extra-vars "host_app=oracle app_id=uc tomcat_port=8083"
