---
- hosts: all
  user: root
  vars:
   - jdk_home: /home
   - jdk_version: jdk-7u80
   - jdk_dest_Home: jdk1.7.0_80
  tasks:
    - name : /usr/java dir
      file:  path=/usr/java/ state=directory group=root owner=root mode=755
    - name : '{{ jdk_version }}-linux-x64.tar.gz'
      unarchive : src={{ jdk_home }}/{{ jdk_version }}-linux-x64.tar.gz dest=/usr/java/ creates={{ jdk_dest_Home }}
      notify:
        - modify_profile
  handlers:
    - name: modify_profile
      shell: echo 'export JAVA_HOME=/usr/java/jdk1.7.0_80' >> /etc/profile && echo 'export JRE_HOME=$JAVA_HOME/jre' >> /etc/profile && echo 'export JAVA_BIN=$PATH:$JAVA_HOME/bin' >> /etc/profile && echo 'export PATH=$JAVA_HOME/bin:$PATH' >> /etc/profile && echo 'export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/jre/lib:$JAVA_HOME/lib' >> /etc/profile && echo 'export JAVA_HOME JAVA_BIN PATH CLASSPATH' >> /etc/profile
