---
- hosts: all
  user: root
  vars:
   - jdk_home: /home
   - jdk_version: jdk-7u80
   - jdk_dest_Home: jdk1.7.0_80
   - jre_home: "$JAVA_HOME/jre"
   - java_bin: "$PATH:$JAVA_HOME/bin"
   - java_env_path: "$JAVA_HOME/bin:$PATH"
   - java_env_class_path: ".:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/jre/lib:$JAVA_HOME/lib"
  tasks:
    - name : /usr/java dir
      file:
        path: "/usr/java/"
        state: directory
        group: root
        owner: root
        mode: "755"
    - name : '{{ jdk_version }}-linux-x64.tar.gz'
      unarchive :
        src: "{{ jdk_home }}/{{ jdk_version }}-linux-x64.tar.gz"
        dest: "/usr/java/"
        group: root
        owner: root
        creates: "{{ jdk_dest_Home }}"
      notify:
        - modify_profile
  handlers:
    - name: modify_profile
      lineinfile:
        path: /etc/profile        
        line: "{{item}}"
      with_items:
        - "export JAVA_HOME=/usr/java/{{jdk_dest_Home}}"
        - "export JRE_HOME={{jre_home}}"
        - "export JAVA_BIN={{java_bin}}"
        - "export PATH={{java_env_path}}"
        - "export CLASSPATH={{java_env_class_path}}"
        - "export JAVA_HOME JAVA_BIN PATH CLASSPATH"
