---
- hosts: nginx
  remote_user: root
  vars:
    - log_path: /var/log/nginx
    - serverName: www.gky.com
    - epel_6: http://mirrors.aliyun.com/repo/epel-6.repo
  tasks:
    - name: "wget {{epel_6}}"
      get_url:
        url: "{{epel_6}}"
        dest: /etc/yum.repos.d/epel-6.repo
        backup: yes
      notify:
        makecache
    - name: install nginx
      yum:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - gcc
        - gcc-c++
        - libtool
        - make
        - libtool
        - zlib
        - zlib-devel
        - openssl
        - openssl-devel
        - pcre
        - pcre-devel
        - nginx
    - name: deploy configure
      template:
        src: ../templates/nginx.j2
        dest: /etc/nginx/nginx.conf
        backup: yes
      notify:
         restart_nginx
  handlers:
    - name: restart_nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
    - name: makecache
      shell: yum clean all && yum makecache
