---
- hosts: "{{host_app}}"
  vars:
    - supervisor_configuration_file_path: /etc/supervisor
    - supervisor_include_path: "{{ supervisor_configuration_file_path }}/conf.d"
    - nginx_log_path: /var/log/nginx/access.log
    - nginx_conf_path: /etc/nginx/nginx.conf
  tasks:
    - name: Deploy | {{ host_app }} group
      template:
        src: ../templates/nginx.j2
        dest: "{{ supervisor_include_path }}/nginx.ini"
        backup: yes
      notify:
        update_supervisorctl
      tags: nginx
  handlers:
    - name: update_supervisorctl
      command: supervisorctl update
