---
- hosts: "{{ host_app }}"
  tasks:
    - name: Initial | create directory /etc/zabbix/scripts
      file:
        path: /etc/zabbix/scripts
        state: directory
        mode: "u=rwx,g=rx,o=rx"
    - name: Initial | check zabbix_agentd.conf(Include)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        state: present
        line: "{{ item }}"
      notify: restart zabbix_agentd
      with_items:
        - "Include=/etc/zabbix/zabbix_agentd.d/"
        - "User=qyy"
    - name: Inital | chown |log |run
      file:
        path: "{{ item }}"
        owner: qyy
        group: qyy
        recurse: yes
      with_items:
        - "/var/log/zabbix/"
        - "/var/run/zabbix/"
    - name: Install | deploy tcp_conn_status.{conf,sh}
      copy:
        src: "../templates/{{ item.j2_file }}"
        dest: "{{ item.deploy_file }}"
        mode: "u=rwx,g=rx,o=rx"
        owner: zabbix
        group: zabbix
      notify: restart zabbix_agentd
      with_items:
        - { j2_file: "zabbix_discover_jvm.conf", deploy_file: "/etc/zabbix/zabbix_agentd.d/zabbix_discover_jvm.conf"}
        - { j2_file: "zabbix_discover_jvm.sh", deploy_file: "/etc/zabbix/scripts/zabbix_discover_jvm.sh"}
  handlers:
    - name: restart zabbix_agentd
      service:
        name: zabbix-agent
        state: restarted
        enabled: yes
# 脚本文件获取
# https://github.com/mainiubaba/One/tree/master/zabbix/jvm
# User=name根据自己实际情况更改，name的值是java应用程序的运行用户
# #ansible-playbook deploy_jvm.yml --extra-vars host_app=10.1.1.10
# $ansible-playbook deploy_jvm.yml --extra-vars host_app=10.1.1.10 -s
# 执行后，在服务端测试,有返回值说明成功；没有的话，检查服务是否启动，启动用户是否一致
# zabbix-get -s 10.0.0.10 -k custom.discover.jvm_app | jq .
# 然后在web端导入模板文件
# 最后在对应的主机添加模板，等会看有没有数据，没数据看监控项详情，会有提示。
